---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wedangs2/public_html/klique/wp-content/themes/kamiklique
    - /bin/cp -R css $DEPLOYPATH
    # - /bin/cp -R includes $DEPLOYPATH
    # - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp page-values.php $DEPLOYPATH
    # - /bin/cp page-about.php $DEPLOYPATH
    - /bin/cp page-services.php $DEPLOYPATH
        # - /bin/cp -R js $DEPLOYPATH